### ISSUE TITLE
serverless -  Lambda layers packaging problem

### ISSUE THREAD

**Issue by perzanko** [serverless/serverless-plugin-typescript#122]
Could you please check this bug with layers packaging? Ref: https://github.com/serverless/serverless/issues/5556

**Comment by matt-filion** [comment]
This is causing a us to have to do a lot of work around's. Any eta on this guy?

**Comment by ahummel25** [comment]
Any chance of this getting resolved? Cannot deploy using layers and also using typescript plugin.

**Comment by pgrzesik** [comment]
I'm going to close this one in favor of: https://github.com/serverless/serverless-plugin-typescript/issues/240 as they're about the same problem
