### ISSUE TITLE
plugin compiles functions that do not use node runtime

### ISSUE THREAD

**Issue by vectorjohn** [serverless/serverless-plugin-typescript#198]
If I have a project that uses multiple runtimes (configured individually per function), using this plugin will treat them all as TypeScript and attempt to compile them. This blocks using the plugin in a mixed runtime environment.

**Comment by vectorjohn** [comment]
#197 is my attempt at fixing this. It works when I use it for my case but I may have missed some corner cases.

**Comment by wahlforss** [comment]
I need this also!

**Comment by vectorjohn** [comment]
This is fixed in master (but not in any release yet!).

**Comment by avivshafir** [comment]
why is this closed? I'm getting this error when combining node (typescript) and python runtimes
running the latest version 2.1.4
