### ISSUE TITLE
Missing file in package after migration from package.include to package.patterns

### ISSUE THREAD

**Issue by martinduris** [serverless/serverless-plugin-typescript#231]
Hi,

Serverless deprecated 'package.include' and new 'package.patterns' does not work with 'typescript-plugin-typescript'

- Serverless issue: https://github.com/serverless/serverless/issues/9383
- Example repository: https://github.com/martinduris/serverless-patterns-include

Steps to reproduce
1) not working
- npm i
- sls package
- when i open ZIP file '.serverless/serverless-patterns-include.zip'  i cannot find file 'openapi-doc.yaml' inside 'src' folder

2) working
- Open 'serverless.yaml' and uncomment 'package.include'
- repeat same steps, you should be able to find file included

Thans a lot for help!

**Comment by CrshOverride** [comment]
This one bit me yesterday as well. Currently the Serverless CLI warns about future deprecation when using `include`/`exclude` as part of `package`.

**Comment by tim-oe** [comment]
have hit same issue changing include to patterns fails 
also have the following plugins

  - serverless-localstack
  - serverless-plugin-typescript
  - serverless-plugin-include-dependencies
  - serverless-plugin-common-excludes

**Comment by demsey2** [comment]
any update on this issue?

**Comment by medikoo** [comment]
Will be fixed with https://github.com/prisma-labs/serverless-plugin-typescript/pull/243

**Comment by nake89** [comment]
@JackCuthbert could you have a look at this. Thank you in advance :)
medikoo has made a PR that would fix this: https://github.com/prisma-labs/serverless-plugin-typescript/pull/243
