### ISSUE TITLE
Vulnerability about glob-parent

### ISSUE THREAD

**Issue by matsutake-eg** [serverless/serverless-plugin-typescript#244]
Hello!
I love using this plugin.

Sadly, I found vulnerability about `glob-parent`.
https://github.com/advisories/GHSA-ww39-953v-wcq6

Is there good way for everyone to use this plugin safety?

**Comment by T4ze** [comment]
It seems that there is already a PR (#153) from 2019 relative to this subject and should fix the issue.
@medikoo It would really be nice if this could be rebased and  merged to fix vulnerability issues.

**Comment by medikoo** [comment]
@T4ze thanks for pinging. We've just released v2.0.0 of a plugin that comes with upgraded `globby`

**Comment by matsutake-eg** [comment]
Thank you, @T4ze and @medikoo!
I'll be using this in the future!
