### ISSUE TITLE
Support Serverless 3

### ISSUE THREAD

**Issue by trygveaa** [serverless/serverless-plugin-typescript#263]
Serverless 3.0.0 was released yesterday, it would be great if you could add support for it.

I tried running it with Serverless 3.0.0, and didn't encounter any issues, so maybe it's enough to update the peerDependency version, but I haven't checked in detail if there is any more that needs to be done.

**Comment by medikoo** [comment]
@trygveaa great thanks for opening that, indeed, we somehow forgot to mark it as compatible. I've just prepare PR: https://github.com/serverless/serverless-plugin-typescript/pull/264

It should be followed with a new release today

**Comment by trygveaa** [comment]
Great, thanks!
