### ISSUE TITLE
Is it possible to include files that aren't specifically imported?

### ISSUE THREAD

**Issue by theodorDiaconu** [serverless/serverless-plugin-typescript#266]
I have a mechanism in which I automatically load all the graphql files from a 'graphql' folder. I don't explicitly import these files I extract them based on `__dirname`, however in the `.build` output those files are missing resulting into an error. Is there a way to bypass this or add a hook to it so it copies these files too?

**Comment by theodorDiaconu** [comment]
@medikoo any ideas? thank you!

**Comment by medikoo** [comment]
@theodorDiaconu sorry, my knowledge of this plugin internals is very limited, and unfortunately at this point, I'm unable to invest time into it

**Comment by theodorDiaconu** [comment]
@medikoo got it, thank you.

**Comment by theodorDiaconu** [comment]
After doing additional digging, it seems that behind the scenes they are using ts.createProgram (https://github.com/microsoft/TypeScript-wiki/blob/main/Using-the-Compiler-API.md#a-minimal-compiler) 

This means that we have no way of including 'orphaned' modules. The only solution for me at least is to create a custom serverless plugin.
