### ISSUE TITLE
ignore non nodejs functions

### ISSUE THREAD

**Issue by ronyeh-lb** [serverless/serverless-plugin-typescript#271]
i saw that there was some effort with this issue, any chance we can verify the pr and merge it ?

https://github.com/serverless/serverless-plugin-typescript/pull/197

**Comment by vectorjohn** [comment]
Not to be impatient, but when will this fix make it into a release? I did the work on #197 because I needed this and am still unfortunately running on an old fork I made back then. I'd like to get the latest version :)
